server:
  port: 8080

zuul:
  prefix: /avocashapi
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    
  routes:
    user-service: 
      path: /user/**
      url: http://user-service:8181
      serviceId: user-service
      stripPrefix: false
      sensitiveHeaders:
           
    card-service:
      path: /card/**
      serviceId: card-service
      stripPrefix: false
      sensitiveHeaders:
           
    account-service:
      path: /account/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders:  
      
    transaction-service:
      path: /transaction/**
      serviceId: transaction-service
      stripPrefix: false
      sensitiveHeaders:   
      
    recipient-service:
      path: /recipient/**
      serviceId: recipient-service
      stripPrefix: false
      sensitiveHeaders:
      


  
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      
---
spring:
  profiles: default
  zipkin:
    baseUrl: http://tracing-server:9411
---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411