server:
  port: 8585
  
  spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: default
  zipkin:
    baseUrl: http://tracing-server:9411
---
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      
security:
  oauth2:
    client:
      clientId: recipient-service
      clientSecret: ${RECIPIENT_SERVICE_PASSWORD}
      accessTokenUri: http://user-service:8181/user/oauth/token
      grant-type: client_credentials
      scope: server
      
